//Login
export const REQUEST_AUTH_LOGIN = "REQUEST_AUTH_LOGIN"; 
export const SUCCESS_AUTH_LOGIN = "SUCCESS_AUTH_LOGIN"; 
export const FAIL_AUTH_LOGIN = "FAIL_AUTH_LOGIN"; 

//register
export const REQUEST_AUTH_REGISTER = "REQUEST_AUTH_REGISTER"; 
export const SUCCESS_AUTH_REGISTER = "SUCCESS_AUTH_REGISTER"; 
export const FAIL_AUTH_REGISTER = "FAIL_AUTH_REGISTER"; 

//verify email
export const REQUEST_VERIFY_EMAIL = "REQUEST_AUTH_REGISTER"; 
export const SUCCESS_VERIFY_EMAIL = "SUCCESS_AUTH_REGISTER"; 
export const FAIL_VERIFY_EMAIL = "FAIL_AUTH_REGISTER"; 
