//Login
export const REQUEST_AUTH_LOGIN = "REQUEST_AUTH_LOGIN"; 
export const SUCCESS_AUTH_LOGIN = "SUCCESS_AUTH_LOGIN"; 
export const FAIL_AUTH_LOGIN = "FAIL_AUTH_LOGIN"; 
//Check token
export const REQUEST_CHECK_TOKEN = "REQUEST_CHECK_TOKEN"; 
export const SUCCESS_CHECK_TOKEN = "SUCCESS_CHECK_TOKEN"; 
export const FAIL_CHECK_TOKEN = "FAIL_CHECK_TOKEN"; 

