//Get CATEGORIES
export const REQUEST_GET_CATEGORIES = "REQUEST_GET_CATEGORIES";
export const SUCCESS_GET_CATEGORIES = "SUCCESS_GET_CATEGORIES";
export const FAIL_GET_CATEGORIES = "FAIL_GET_CATEGORIES";
//Get CATEGORY
export const REQUEST_GET_CATEGORY = "REQUEST_GET_CATEGORY";
export const SUCCESS_GET_CATEGORY = "SUCCESS_GET_CATEGORY";
export const FAIL_GET_CATEGORY = "FAIL_GET_CATEGORY";
//Edit CATEGORY
export const REQUEST_EDIT_CATEGORIES = "REQUEST_EDIT_CATEGORIES";
export const SUCCESS_EDIT_CATEGORIES = "SUCCESS_EDIT_CATEGORIES";
export const FAIL_EDIT_CATEGORIES = "FAIL_EDIT_CATEGORIES";
//create CATEGORY
export const REQUEST_CREATE_CATEGORIES = "REQUEST_CREATE_CATEGORIES";
export const SUCCESS_CREATE_CATEGORIES = "SUCCESS_CREATE_CATEGORIES";
export const FAIL_CREATE_CATEGORIES = "FAIL_CREATE_CATEGORIES";
//Delete CATEGORY
export const REQUEST_DELETE_CATEGORIES = "REQUEST_DELETE_CATEGORIES";
export const SUCCESS_DELETE_CATEGORIES = "SUCCESS_DELETE_CATEGORIES";
export const FAIL_DELETE_CATEGORIES = "FAIL_DELETE_CATEGORIES";
