//Get courses
export const REQUEST_GET_COURSES = "REQUEST_GET_COURSES";
export const SUCCESS_GET_COURSES = "SUCCESS_GET_COURSES";
export const FAIL_GET_COURSES = "FAIL_GET_COURSES";
//Get course
export const REQUEST_GET_COURSE = "REQUEST_GET_COURSE";
export const SUCCESS_GET_COURSE = "SUCCESS_GET_COURSE";
export const FAIL_GET_COURSE = "FAIL_GET_COURSE";
//Edit course
export const REQUEST_EDIT_COURSES = "REQUEST_EDIT_COURSES";
export const SUCCESS_EDIT_COURSES = "SUCCESS_EDIT_COURSES";
export const FAIL_EDIT_COURSES = "FAIL_EDIT_COURSES";
//create course
export const REQUEST_CREATE_COURSES = "REQUEST_CREATE_COURSES";
export const SUCCESS_CREATE_COURSES = "SUCCESS_CREATE_COURSES";
export const FAIL_CREATE_COURSES = "FAIL_CREATE_COURSES";
//Delete course
export const REQUEST_DELETE_COURSES = "REQUEST_DELETE_COURSES";
export const SUCCESS_DELETE_COURSES = "SUCCESS_DELETE_COURSES";
export const FAIL_DELETE_COURSES = "FAIL_DELETE_COURSES";
