//Get posts
export const REQUEST_GET_POSTS = "REQUEST_GET_POSTS";
export const SUCCESS_GET_POSTS = "SUCCESS_GET_POSTS";
export const FAIL_GET_POSTS = "FAIL_GET_POSTS";
//Cretae new post
export const REQUEST_CREATE_POSTS = "REQUEST_CREATE_POSTS";
export const SUCCESS_CREATE_POSTS = "SUCCESS_CREATE_POSTS";
export const FAIL_CREATE_POSTS = "FAIL_CREATE_POSTS";
//Cretae new post
export const REQUEST_UPDATE_POSTS = "REQUEST_UPDATE_POSTS";
export const SUCCESS_UPDATE_POSTS = "SUCCESS_UPDATE_POSTS";
export const FAIL_UPDATE_POSTS = "FAIL_UPDATE_POSTS";
//Get single post
export const REQUEST_GET_POST = "REQUEST_GET_POST";
export const SUCCESS_GET_POST = "SUCCESS_GET_POST";
export const FAIL_GET_POST = "FAIL_GET_POST";
//Delete post
export const REQUEST_DELETE_POSTS = "REQUEST_UPDATE_POSTS";
export const SUCCESS_DELETE_POSTS = "SUCCESS_UPDATE_POSTS";
export const FAIL_DELETE_POSTS = "FAIL_UPDATE_POSTS";
//Get post category
export const REQUEST_GET_POSTS_CATEGORY = "REQUEST_GET_POSTS_CATEGORY";
export const SUCCESS_GET_POSTS_CATEGORY = "SUCCESS_GET_POSTS_CATEGORY";
export const FAIL_GET_POSTS_CATEGORY = "FAIL_GET_POSTS_CATEGORY";
//Crate post category
export const REQUEST_CREATE_POSTS_CATEGORY = "REQUEST_CREATE_POSTS_CATEGORY";
export const SUCCESS_CREATE_POSTS_CATEGORY = "SUCCESS_CREATE_POSTS_CATEGORY";
export const FAIL_CREATE_POSTS_CATEGORY = "FAIL_CREATE_POSTS_CATEGORY";
//Crate post category
export const REQUEST_UPDATE_POSTS_CATEGORY = "REQUEST_UPDATE_POSTS_CATEGORY";
export const SUCCESS_UPDATE_POSTS_CATEGORY = "SUCCESS_UPDATE_POSTS_CATEGORY";
export const FAIL_UPDATE_POSTS_CATEGORY = "FAIL_UPDATE_POSTS_CATEGORY";
//Delete post
export const REQUEST_DELETE_CATEGORY = "REQUEST_UPDATE_CATEGORY";
export const SUCCESS_DELETE_CATEGORY = "SUCCESS_UPDATE_CATEGORY";
export const FAIL_DELETE_CATEGORY = "FAIL_UPDATE_CATEGORY";
//Get post Tags
export const REQUEST_GET_POSTS_TAG = "REQUEST_GET_POSTS_TAG";
export const SUCCESS_GET_POSTS_TAG = "SUCCESS_GET_POSTS_TAG";
export const FAIL_GET_POSTS_TAG = "FAIL_GET_POSTS_TAG";