//Get all users
export const REQUEST_GET_USERS = "REQUEST_GET_USERS"; 
export const SUCCESS_GET_USERS = "SUCCESS_GET_USERS"; 
export const FAIL_GET_USERS = "FAIL_GET_USERS"; 
//Get all instructors
export const REQUEST_GET_INSTRUCTORS = "REQUEST_GET_INSTRUCTORS"; 
export const SUCCESS_GET_INSTRUCTORS = "SUCCESS_GET_INSTRUCTORS"; 
export const FAIL_GET_INSTRUCTORS = "FAIL_GET_INSTRUCTORS"; 
//Get user by ID
export const REQUEST_GET_USER_ID = "REQUEST_GET_USER_ID"; 
export const SUCCESS_GET_USER_ID = "SUCCESS_GET_USER_ID"; 
export const FAIL_GET_USER_ID = "FAIL_GET_USER_ID"; 
//Update user by ID
export const REQUEST_UPDATE_USER = "REQUEST_UPDATE_USER"; 
export const SUCCESS_UPDATE_USER = "SUCCESS_UPDATE_USER"; 
export const FAIL_UPDATE_USER = "FAIL_UPDATE_USER"; 
//Update user by ID
export const REQUEST_UPDATE_USER_AVATAR = "REQUEST_UPDATE_USER_AVATAR"; 
export const SUCCESS_UPDATE_USER_AVATAR = "SUCCESS_UPDATE_USER_AVATAR"; 
export const FAIL_UPDATE_USER_AVATAR = "FAIL_UPDATE_USER_AVATAR";
//Delete user by ID
export const REQUEST_DELETE_USER = "REQUEST_DELETE_USER"; 
export const SUCCESS_DELETE_USER = "SUCCESS_DELETE_USER"; 
export const FAIL_DELETE_USER = "FAIL_DELETE_USER";
//Create user meta
export const REQUEST_CREATE_USER_META = "REQUEST_CREATE_USER_META"; 
export const SUCCESS_CREATE_USER_META = "SUCCESS_CREATE_USER_META"; 
export const FAIL_CREATE_USER_META = "FAIL_CREATE_USER_META"; 
//Update user meta
export const REQUEST_UPDATE_USER_META = "REQUEST_UPDATE_USER_META"; 
export const SUCCESS_UPDATE_USER_META = "SUCCESS_UPDATE_USER_META"; 
export const FAIL_UPDATE_USER_META = "FAIL_UPDATE_USER_META"; 
//Get user meta
export const REQUEST_GET_USER_META = "REQUEST_GET_USER_META"; 
export const SUCCESS_GET_USER_META = "SUCCESS_GET_USER_META"; 
export const FAIL_GET_USER_META = "FAIL_GET_USER_META"; 
//Create new user
export const REQUEST_CREATE_USER = "REQUEST_CREATE_USER"; 
export const SUCCESS_CREATE_USER = "SUCCESS_CREATE_USER"; 
export const FAIL_CREATE_USER = "FAIL_CREATE_USER"; 